spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petshop_test}
    username: ${DB_USERNAME:petshop_db_username}
    password: ${DB_PASSWORD:petshop_db_password}
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/petshop-master.xml

logging:
  level:
    root: info
    org.springframework:
      data: debug
    me.giorgirokhadze: debug
